### ISSUE TITLE
Azure Application Insights Target

### ISSUE THREAD

**Issue by toburger** [logary/logary#133]
Hi, I have a suave project running on Azure and a logary target for Azure Application Insights would be welcome.
I could write the target and make a PR, but ATM it has a low priority to us.
It should be similar to the AWS Cloud Watch target so I hope I can get some inspiration from that, but I'm pretty new to suave and also don't know much about Azure Application Insights, so please be patient with me. ;)

**Comment by haf** [comment]
@toburger If you have any questions on how to build the target, don't hesitate to ask here.

**Comment by haf** [comment]
I put up an offer here https://github.com/logary/logary#want-your-saas-logging-service-as-a-target if you're interested

**Comment by christolo** [comment]
Any update on this? I'd be willing to help out if there's any interest.

**Comment by toburger** [comment]
Sorry for not replying on this topic anymore.
Due to time constraints on our project we've chosen to use Isaac Abrahams solution which turns out to work very well for us.
Here is an example of the solution: https://github.com/isaacabraham/azure-fsharp-helpers

**Comment by christolo** [comment]
Great, thanks! I'll check it out.

**Comment by Thorium** [comment]
I'm also interested of this... But I'm not using Suave. 
Maybe this would be just a few lines of code to write a target. 
Something like https://github.com/Microsoft/ApplicationInsights-dotnet-logging
I'll dig this a bit more soon.
