### ISSUE TITLE
getLogger can block under some circumstances

### ISSUE THREAD

**Issue by mavnn** [logary/logary#136]
``` fsharp
      member x.getLogger name =
        name |> getLogger inst.registry |> run
```

It turns out the default getLogger implementation for LogManager can block if used within an existing Hopac workflow, but the interface doesn't include an async version.

The fix for this is simple but a breaking change to any other implementations of the interface; are we happy for this to go into a point release?

https://github.com/logary/logary/blob/master/src/Logary/Configuration_Config.fs#L207

**Comment by haf** [comment]
Yes, because Logary is explicitly Alpha right now. It should be transformed into a `Task<Logger>`, no? See the existing C# wrapper lib for details on how to transform the job.

**Comment by mavnn** [comment]
Why not a Job<Logger>? We already have one Job<_> Async method on the interface.

**Comment by mavnn** [comment]
Or should that become a Task as well?

**Comment by mavnn** [comment]
I've made it Job for now, we can review the whole interface later if we decide they should both be Tasks
