### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by haf** [logary/logary#14]
Write complete and full documentation for all metrics, probes, health checks, targets and adapters.

Normalise the form of comments across the code to generate well-written en-GB documentation. E.g. by always capitalising the first character of a sentence, writing proper punctuation etc.

Document how it's all configured at the start in F#, in C#, make sure C# API is as expressive. Add 'CompiledName' attributes to functions that need to be used from C#.

Describe the running of metrics, how they are sampled, how they differ from probes.

**Comment by theor** [comment]
An actual tutorial would be a good start!

**Comment by haf** [comment]
That's very true, but I'm lacking a bit in time as of late. Have you found the examples in the source?

**Comment by theor** [comment]
I did, thank you ! A more visible link could help :)

**Comment by Thorium** [comment]
https://logary.github.io/ is not for current 4.x version. For version 4 there is very little anything available on the internet.

**Comment by haf** [comment]
@Thorium Yes, that's correct. The main changes from an API stand-point are:
 
 - LogLine -> Message
 - LogLine.setData -> Message.setField
 - Logger returns things that you have to `Hopac.Job.Global.start`
 - Performance is a lot faster
 - Removed strange dependency on FSharp.Actors and Newtonsoft
 - And the internals are completely different, but that doesn't concerns the external API very much.
