### ISSUE TITLE
Perf: Value.ofObject, Map.ofObject

### ISSUE THREAD

**Issue by haf** [logary/logary#154]
Investigate what performance gains could be had by moving to a smarter reflection for:
- [Value.ofObject](https://github.com/logary/logary/blob/master/src/Logary/DataModel.fs#L188)
- [Map.ofObject](https://github.com/logary/logary/blob/master/src/Logary/Internals.fs#L174)

E.g. by using [TypeShape](https://eiriktsarpalis.wordpress.com/2016/08/05/typeshape-practical-generic-programming-in-f/) – [from Eirik](https://github.com/eiriktsarpalis/TypeShape/blob/master/samples/printer.fsx).

Micro-benchmark required, around these particular functions.

Useful, because this code is called on the same thread as the caller.

**Comment by lust4life** [comment]
in v5, `Value.ofObject` is no longer needed, and the usage scenarios of `Map.ofObject` is probably not a lot, maybe no need do this benchmark

**Comment by haf** [comment]
You're right, let's close this then. Is the idea that the user writes his/her own picklers with FsPickler to serialise for any particular target he/she is writing?
