### ISSUE TITLE
Colourised console in Logary proper

### ISSUE THREAD

**Issue by haf** [logary/logary#163]
I'd like to pull in the colourised console target into Logary proper; not just have it in the Facade.

**Comment by haf** [comment]
I've implemented the global semaphore in `Facade` and `Adapters.Facade` and `Targets_Core`. All that's left is to properly parse and then colourise in the console target. Docs written in the [`README`](https://github.com/logary/logary#console-logging), too.

**Comment by adamchester** [comment]
I've opened #165, the trick is Logary proper has some slightly more complicated field types to deal with. Thoughts?

**Comment by haf** [comment]
Let me get back to you later today

**Comment by haf** [comment]
You can consume a sequence of leafs from this function to avoid recursion: https://github.com/logary/logary/blob/master/src/Logary/Formatting.fs#L92

**Comment by haf** [comment]
If it's just the fields, then if you point me in the right direction then I can sort out the different cases...

**Comment by adamchester** [comment]
I think you have push access to the PR now, otherwise hopefully I can get back to this in a few days. Feel free to tackle anything you like 👍 Or leave it for me 👍

**Comment by haf** [comment]
I think this is done now :) 💯
