### ISSUE TITLE
Consider a new log event API for templated messages

### ISSUE THREAD

**Issue by adamchester** [logary/logary#184]
I'm considering ways of making it easier to use templated events with embedded structured fields. This proposal below has the following attributes:
 1. Doesn't interfere much with any existing code
 1. Provides a standard way to associate the _types_ of format template arguments with the event itself
 1. Removes the need to parse the template each time the event happens, by generating a new func that already has a reference to the parsed template.

```fsharp
type Message with
  static member private createTemplate level format = 
    let template = Parser.parse format
    fun args ->
      let fields = LogaryCapturing.capture template args
      Message.eventX format level |> Message.setFieldValues fields

  static member templateEvent<'T> (level : LogLevel, format : string) : ('T -> Message) =
    let template = Message.createTemplate level format
    fun (v : 'T) -> template [| v |]

  static member templateEvent<'T1, 'T2> (level : LogLevel, format : string) : ('T1 -> 'T2 -> Message) =
    let template = Message.createTemplate level format
    fun (v1 : 'T1) (v2 : 'T2) -> template [| v1; v2; |]

  static member templateEvent<'T1, 'T2, 'T3> (level : LogLevel, format : string) : ('T1 -> 'T2 -> 'T3 -> Message) =
    let template = Message.createTemplate level format
    fun (v1 : 'T1) (v2 : 'T2) (v3 : 'T3) -> template [| v1; v2; v3; |]
```

The usage would be:
```fsharp
 let userLoggedIn = Message.templateEvent<string> (Info, "{userName} logged in")
 userLoggedIn "haf" |> Logger.logSimple logger
 userLoggedIn "adam" |> Logger.logSimple logger
```

```fsharp
testCase "Formatting.templateEvent<*> works" <| fun _ ->

  let logEventGuid =      Message.templateEvent<Guid>           (Info, "This special {Guid} is logged")
  let logEventStringInt = Message.templateEvent<string, int>    (Warn, "This {gramaticalStructure} contains {wordCount} words.")
  let logEventIntIntInt = Message.templateEvent<int, int, int>  (Error, "There a 3 numbers: {one} {two} {three}")

  (because "fields are matched left-to-right in message template" <| fun () ->
    extractFormatFields (logEventGuid Guid.Empty)
    , extractFormatFields (logEventStringInt "sentence" 30)
    , extractFormatFields (logEventIntIntInt 1 2 3))
  |> should equal (
      ("This special {Guid} is logged",
          Set [ "Guid", Field (String ("00000000-0000-0000-0000-000000000000"), None) ]),
      ("This {gramaticalStructure} contains {wordCount} words.",
          Set [ "gramaticalStructure", Field (String "sentence", None)
                "wordCount", Field (Int64 30L, None) ]),
      ("There a 3 numbers: {one} {two} {three}",
          Set [ "one", Field (Int64 1L, None)
                "two", Field (Int64 2L, None)
                "three", Field (Int64 3L, None) ])
    )
  |> thatsIt
```

**Comment by adamchester** [comment]
What would be good is if the event didn't have to capture the fields, allocate an array, set the message fields, etc in the case when the log level is higher than the event, but I'm not sure how best to achieve that.

**Comment by adamchester** [comment]
Current using a slightly more optimised version of this to test #170 

https://github.com/logary/logary/pull/170/files#diff-47eb8ac96e0b339e357ddd7566d4da0fR55

**Comment by haf** [comment]
I think we should merge these changes.

You're considering the allocations that happen when `Parser.parse` is called?

**Comment by adamchester** [comment]
The main thing [here](https://github.com/logary/logary/pull/170/files#diff-47eb8ac96e0b339e357ddd7566d4da0fR55) is associating parameter types with the template.

What I was [wondering above] is how these functions returned from `Message.templateEvent<*>` could be used to write events at level `Verbose` or `Debug`, and avoiding doing unncessary work when the logging level would cause them to be discarded (and not logged).

I noticed that [`eventX`](https://github.com/logary/logary#using-logary-in-a-library) does something along these lines, right?

**Comment by haf** [comment]
No, `eventX` is just a reordered version that, when used in conjunction with `LogLevel -> Message` `Logger` interface/module functions, do lazy evaluation of the passed lambda.

**Comment by adamchester** [comment]
Yes that's what I'm thinking of... generating a method than can be used in conjunction with `LogLevel -> Logger`

**Comment by adamchester** [comment]
(Avoid doing all the capturing work in a succinct way)

**Comment by haf** [comment]
Currently merged to master.
