### ISSUE TITLE
Reflection of F# discriminated union case fields

### ISSUE THREAD

**Issue by haf** [logary/logary#187]
# It should be possible to get nice output from DU case fields. Otherwise, a DU case that contains fields will output like this:

<img width="666" alt="screen shot 2016-10-07 at 21 25 40" src="https://cloud.githubusercontent.com/assets/193115/19202870/aed1499c-8cd4-11e6-91d4-be1d3a3359ab.png">

**Comment by haf-lynx** [comment]
Fixed with 4da2ee50b27e48e6cd1ad638306118dec1892a15
