### ISSUE TITLE
LiterateConsole prints funky Gauges

### ISSUE THREAD

**Issue by haf-lynx** [logary/logary#192]
```
[02:03:15 DBG] Metric (guage) 81449400 s / 1000000000.000000 Lynx.X.Y.Z.GetUnfinishedMessages)
```

When doing a C#

``` csharp
using (logger.TimeScope("GetUnfinishedMessages"))
  ;
```

/cc @adamchester

**Comment by adamchester** [comment]
What would be nice output here?  

I'm not too familiar with `TimeScope`

**Comment by haf-lynx** [comment]
It just logs a Gauge in s/10^9.

Nice output would be `[02:03:15 DBG] Lynx.X.Y.Z.GetUnfinishedMessages 81.449 ms (Gauge)`

**Comment by haf** [comment]
Fixed.
