### ISSUE TITLE
Wrong date calculation from EpochNanoSeconds

### ISSUE THREAD

**Issue by Dzoukr** [logary/logary#195]
LiterateConsole (empty) uses this function

https://github.com/logary/logary/blob/ac87204d9555ce8e44d44248065b3ca9796bc9b3/src/Logary/Targets_Core.fs#L474-L476

``` fsharp
fun provider utcTicks ->
  DateTimeOffset(utcTicks, TimeSpan.Zero).LocalDateTime.ToString("HH:mm:ss", provider),
  Tokens.Subtext
```

But utcTicks is EpochNanoSeconds , which leads to wrong date.

Something like this should be used:

``` fsharp
fun (provider:IFormatProvider) (utcTicks:EpochNanoSeconds) -> 
    let ms = utcTicks / 1000000L |> float
    (new System.DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).AddMilliseconds(ms).ToString("HH:mm:ss", provider), Tokens.Subtext
```

I wanted to send PR, but there are more places with conversion. I think that helper functions from Facade (https://github.com/logary/logary/blob/a131dce06cd491e75db74b7c2467d84814d81200/src/Logary.Facade/Facade.fs#L125-L148) could be used. What do you guys think?

**Comment by haf** [comment]
Fixed, verification by yourself would be nice. Releasing a new version.

**Comment by Dzoukr** [comment]
Ok, I definitely will. Waiting for the new release :)

**Comment by haf** [comment]
v4.0.180 is released

**Comment by Dzoukr** [comment]
Well, that is strange - I can see only v4.0.160 on Nuget - https://www.nuget.org/packages/Logary/
Also GH shows the latest release as 160 - https://github.com/logary/logary/releases

**Comment by haf** [comment]
Ah, yes. You're quite right. I'll get back to you shortly.

**Comment by haf** [comment]
So... Shortly was = rewriting all tests to use Expecto... Finally done with that. Currently compiling and releasing, and it should be indexed by nuget.org in 20 minutes from now.

**Comment by Dzoukr** [comment]
Thanks @haf, I tryied to verify and it is still there. Default (empty) LiterateConsole still uses the old implementation?

https://github.com/logary/logary/blob/master/src/Logary/Targets_Core.fs#L476-L478

**Comment by haf** [comment]
You're right again. Sorry. This time around I have a unit test and have linked this issue.

**Comment by haf** [comment]
Should be fixed.
