### ISSUE TITLE
Comparison feedback

### ISSUE THREAD

**Issue by nblumhardt** [logary/logary#198]
Hey Logary folks! As promised, some notes on the Serilog comparison. Some of the Logary features here are really exciting by the way - you guys are really pushing the state-of-the-art forwards, love it!

Vis: https://github.com/logary/logary#comparison-with-serilog

> Logary was built from running high-throughput distributed systems 24/7 in production and has learnt its lessons

Not sure this is actually a point of comparison; Serilog's running in some pretty enormous systems in production, including things like high-throughput ticket sales and gaming. The statement is fact, but it seems to imply the opposite state-of-affairs for Serilog without qualifying it.

> Targets in Logary tend to use IO completion ports/async-as-"green threads", AFAIK Sinks are primarily running and calling out using synchronous/blocking APIs

Sinks are plugged into Serilog and use a variety of mechanisms. Network-based sinks generally use non-blocking APIs, though since most high-latency I/O happens on background threads we don't go out of our way to avoid blocking them.

It's tough to word this one, because I know Logary has a particularly strong focus on this point. If you consider that Serilog uses `HttpClient` for many of its sinks, which is strictly non-blocking, it's actually impossible for us to call out using synchronous/blocking APIs. No better suggestion from me though, sorry :-)

> Logary's C# API doesn't support misconfiguring Logary, because it's been built with chaining types together (going beyond the return this pattern).

Not sure Serilog's does either - e.g.

```csharp
var log = new LoggerConfiguration()
    .WriteTo.File("log.txt")
    .MinimumLevel.Debug()
    .CreateLogger();

// Reorder clauses, compiles:

var log = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.File("log.txt")
    .CreateLogger();

// Nonsense, does not compile:

var log = new LoggerConfiguration()
    .WriteTo.Debug()
    .MinimumLevel.File("log.txt")
    .CreateLogger();
```

Though it's flexible about the order of configuration items, both of the accepted forms will do pretty much what they say they will. `MinimumLevel.File()` is rejected because Serilog also uses distinct types to go beyond "return this".

> Logary supports Targets that batch, out of the box

Serilog does also, though the batching policy is part of the sink rather than part of the pipeline. `PeriodicBatchingSink` is an out-of-the-box Serilog feature. Would it be more accurate to say that batching in Logary is a policy available to the user, while in Serilog it's determined by the sink author?

> Both are awesome and @nblumhardt is an awesome dude. Use whichever you feel most comfortable with!

I fully endorse this statement ;-) ... Though Serilog is a community-driven project, so it's probably not fair to list my name here. Thanks though!

(cc @adamchester, who's contributed to both of these.)

**Comment by haf** [comment]
Thanks for the excellent input!

I've reworded the point about targets' blocking:
> Targets in Logary tend to use IO completion ports/async-as-"green threads", AFAIK Sinks are  running and calling out using synchronous/blocking APIs to a larger extent.

The batching and config points now also mention Serilog.

Thanks for the praise too =). Tell me if there's something else that's counter-factual.

**Comment by nblumhardt** [comment]
👍 thanks @haf - all the best with the project!
