### ISSUE TITLE
WIP

### ISSUE THREAD

**Issue by haf** [logary/logary#203]
- [ ] Stub test for all modules
 - [ ] Stub tests for all functions in all modules
 - [ ] Move reflection to TypeShape
 - [ ] Move https://github.com/messagetemplates/messagetemplates-fsharp/tree/master/test/FsMessageTemplates.Tests into Logary
 - [ ] Rewrite FsMessageTemplates with FParsec (which is a dependency)
 - [x] Support bisecting TimeSpan.
 - [ ] Test TimeSpan

**Comment by lust4life** [comment]
`Support bisecting TimeSpan.` implemented in #219
