### ISSUE TITLE
Google Cloud Logging Target

### ISSUE THREAD

**Issue by ctaggart** [logary/logary#213]
I would love to see a [Google Cloud Logging](https://cloud.google.com/logging/) target for Logary. There is [a Log4net Appender](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Logging.V2/Google.Logging.Log4Net) in beta. Here is how to[ use it from C#](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/466#issuecomment-262877086).

**Comment by baronfel** [comment]
I'm implementing this, at least in a basic form.

**Comment by lust4life** [comment]
seems merged.
