### ISSUE TITLE
Make the LiterateConsoleTarget use Global semaphore instead of new obj

### ISSUE THREAD

**Issue by theimowski** [logary/logary#225]
Refers to https://github.com/haf/expecto/pull/40

Should it use `Global.semaphore`? The problem is `Global` module depends on `LiterateConsoleTarget` [here](https://github.com/logary/logary/blob/master/src/Logary.Facade/Facade.fs#L765), so we'd either have to make a recursive dependency or somehow parametrize one or another?

What's your take on this @haf?

**Comment by haf** [comment]
I say, let's add a c'tor overload that takes a `unit -> obj` function and make `config` and `defaultConfig` mutually recursive if that works...

**Comment by theimowski** [comment]
Closing as I managed to get stuff working without this change
