### ISSUE TITLE
Facade LiterateConsole target: allow arbitrary log line prefix

### ISSUE THREAD

**Issue by adamchester** [logary/logary#230]
In the Facade `LiterateConsole`, it currently only [supports a single way to render the log line prefix](https://github.com/logary/logary/blob/8fe3fce3f7d2602f2a4dc27419edfbce09c28a82/src/Logary.Facade/Facade.fs#L623) out to the console. However, in some cases, line prefix/template (e.g. `[10:01:55 INF] {message}`) doesn't make a lot of sense. It would be nice if could be easily configured differently.

@haf just raising this issue first in case you think it's not worthwhile. I obviously think it's worthwhile, and I don't *think* it will introduce too much complexity, but do you have any opinion at this early stage?

**Comment by haf** [comment]
+1 – go ahead

**Comment by adamchester** [comment]
[progress](https://github.com/logary/logary/commit/3cdcc582de659247d74a9cacebd4084e0b3bb2a4)

**Comment by adamchester** [comment]
Closed via #234
