### ISSUE TITLE
Logary and logstash integration

### ISSUE THREAD

**Issue by alexey-belous** [logary/logary#235]
I've been trying to set up following logging stack: Logary > Logstash > Solr > Banana and I've faced up with an issue related to serialization of event fields. See details in this [question](https://stackoverflow.com/questions/42808058/logary-and-logstash-integration).

It is possible to adjust serialization of event fields in the Logary by some way to make them format like this "field_name: field_value"? It would allow Solr to search by these fields and replace placeholders of the log message by values of these fields.

Logary config:
```use logary = 
        withLogaryManager "webapp" (
                withTargets [
                    Logstash.create (Logstash.LogstashConf.create ("tcp://127.0.0.1:2120", false, Logstash.LogstashMode.PUSHPULL )) "logstash"
                    Console.create Console.empty "console"
                ] >>
                withRules [
                    Rule.createForTarget "logstash"
                    Rule.createForTarget "console"
                ]
            )
        |> run
```

Logstash config:
```
input {
  zeromq {
    topology => "pushpull"
    mode => "server"
    address => ["tcp://0.0.0.0:2120"]
  }
}
output {
  solr {
    url  => "http://localhost:8983/solr/logs"
    flush_size => 10
  }
  stdout { codec => rubydebug }
}
```

Solr document example:
```
{
    "context":["{}"],
    "fields":["{\"caller\"=>{\"value\"=>\"Suave.Web.split\"}, \"offset\"=>{\"value\"=>{\"Int64\"=>344064}}, \"segmentCount\"=>{\"value\"=>{\"Int64\"=>99}}}"],
    "level":["verbose"],
    "name":["Suave.Sockets.BufferManager"],
    "timestamp":[1489486144686315000],
    "value":["{\"event\"=>\"Freeing buffer at {offset} from {caller}. Free segments {segmentCount}.\"}"],
    "host":["localhost"],
    "id":"2f9fead8-806a-4484-843f-7558783de4af",
    "event_timestamp":["2017-03-14T10:09:04.686Z"],
    "_timestamp":["2017-03-14T10:09:04.686Z"],
    "_version":[1],
    "_version_":1561839425271365632 }
```

Thanks for help.

**Comment by haf** [comment]
The logary implementation is really *very* simple:

 - First serialise to an object: https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.Logstash/Targets_Logstash.fs#L46-L48
 - Then send the JSON: https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.Logstash/Targets_Logstash.fs#L113

My guess: you need to make logstash interpret your input as JSON. Since this is a question and not an actual issue in Logary, I'm closing it for now. Feel free to reply.

**Comment by alexey-belous** [comment]
@haf , thanks for your reply.

I've debugged into the code that you sent and it seems that this behavior provided by Logary. See serialized event:
```
{
    "@timestamp": "2017-03-15T15:02:55.0440463+00:00",
    "@version": "1",
    "context": {},
    "fields": {
        "totalBytes": {
            "value": {
                "Int64": 827392
            }
        }
    },
    "level": "debug",
    "name": "Suave.Sockets.BufferManager",
    "timestamp": 1489590175044046300,
    "value": {
        "event": "Initialising BufferManager with {totalBytes}"
    }
}
```

This event comes through 0MQ to the Logstash, and then I'm trying to make all nested fields of an event as fields of the event directly, to be able to save it into the Solr. The problem exactly in this step. I cannot transform the content of the "fields" field due to their structure is too complicated. I.e. I'm expecting the following transformed event:

```
{
    "@timestamp": "2017-03-15T15:02:55.0440463+00:00",
    "@version": "1",
    "context": {},
    "totalBytes": 827392,
    "level": "debug",
    "name": "Suave.Sockets.BufferManager",
    "timestamp": 1489590175044046300,
    "event": "Initialising BufferManager with {totalBytes}"
}

```

Maybe I'm going in the wrong direction and there is a more easiest way to do it?

**Comment by haf** [comment]
Well, it's rather easy to fix. I had five minutes over so I fixed your issue. You'll have to PR the branch though so I can release it! ;)

https://github.com/logary/logary/tree/feature/parametise-serialiser

**Comment by alexey-belous** [comment]
@haf , It seems that there were some syntax errors in the PR. And when I've been trying to fix them I've come up with another solution. I think serialization of the message fields should stay as is. I'll create another PR with the ability to replace placeholders in the event message by their values like in the [Logary.Targets.Mailgun](https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.Mailgun/Targets_Mailgun.fs#L29)

What do you think?

**Comment by haf** [comment]
If you wish – it's just an optional config parameter in a stand-alone target; so it's very cheap and local code to change. Tell me if you need assistance.
