### ISSUE TITLE
question about some code in registry shutdown

### ISSUE THREAD

**Issue by lust4life** [logary/logary#237]
hello,

i see logary will cancel the schedules when shutdow registry in [Registry.fs](https://github.com/logary/logary/blob/master/src/Logary/Registry.fs#L221) , does here run the same thing twice, or did i miss someting ?

```fsharp
      /// In the shutdown state, the registry doesn't respond to messages, but rather tries to
      /// flush and shut down all targets, doing internal logging as it goes.
      let shutdown state (ackCh : Ch<unit>) (nack : Promise<unit>) = job {
        do! logger.infoWithBP (eventX "Shutting down polling of the metrics")
        do! state.schedules |> List.traverseJobA (snd >> Cancellation.cancel) |> Job.Ignore

        do! logger.infoWithBP (eventX "Cancelling schedules")
        for (_, x) in state.schedules do
          do! Cancellation.cancel x
```

any reply will be thankful.

**Comment by haf** [comment]
No, you're pretty much spot on there. :) Well spotted, that's a bug.

**Comment by haf** [comment]
Also, note https://github.com/logary/logary/tree/feature/live-wpc-reconfigure is rewriting this if you want to help work out how to write the in-memory stream processing engine https://github.com/logary/logary/blob/feature/live-wpc-reconfigure/src/tests/Logary.Tests/Engine.fs

**Comment by lust4life** [comment]
@haf  Thanks for your reply, i will check it.

 btw awesome work. 👍
