### ISSUE TITLE
Logary handshakes with Logstash, but doesn's send log messages over TCP

### ISSUE THREAD

**Issue by valpetrov** [logary/logary#238]
Tested the entire pipeline with Logstash Service running on port 11939 with 
**Logary v3.6.1** -> Logstash service and the messages flow through **successfully**
` withLogary "logstash-sample" (
              withTargets [
                Logstash.create (Logstash.LogstashConf.Create("myhost", 11939us)) "logstash"
                Debugger.create Debugger.empty "debugger"
              ] >>
              withRules [
                Rule.createForTarget "logstash"
                {Rule.createForTarget "debugger" with level = LogLevel.Debug}
              ] >>
              withInternalTargets Verbose [
                Debugger.create (Debugger.empty) "console"
              ]
            ) |> Async.RunSynchronously`

**with version 
Logary v4.0.311** 
`withLogaryManager "logstash-sample" (
              withTargets [
                Logstash.create (Logstash.LogstashConf.create ("tcp://myhost:11939", false, Logstash.LogstashMode.PUSHPULL) ) "logstash"
                Debugger.create Debugger.empty "debugger"
              ] >>
              withRules [
                Rule.createForTarget "logstash"
                {Rule.createForTarget "debugger" with level = LogLevel.Debug}
              ] >>
              withInternalTargets Verbose [
                Debugger.create (Debugger.empty) "console"
              ]
            ) |> run`

The result (verified by sniffing packet traffic w/ wireshark) is that the TCP connection gets established to the correct port. However, writing messages to the logger:
`Message.event Logary.LogLevel.Error (sprintf "%A" m)
            |> log.logSimple`
does not actually push a message to the service. The message simply never leaves the client.

**Comment by haf** [comment]
Yes, you're right. We moved to zmq over TCP in v4 (major change).

**Comment by valpetrov** [comment]
The documentation and PUSHPULL options seems to suggest that this is still a viable option to connect to Logstash. 
Is there any updated documentation or sample code to configuring the pipeline in v4.x ?

Thanks

**Comment by haf** [comment]
Yes you can but via zmq. How about I take two hours out of my day tomorrow and write you a tutorial/guide at my normal rate?
