### ISSUE TITLE
Add message.name to literate logger

### ISSUE THREAD

**Issue by haf** [logary/logary#241]
```
    @ [ " ", Subtext
        "<", Punctuation
        String.concat "." message.name, Subtext
        ">", Punctuation
      ]
```

in `literateDefaultTokeniser`.

**Comment by adamchester** [comment]
Are we talking about Logary _proper_ here?

In the Facade, we can change the `outputTemplate` to include the `{source}` value:
```fsharp
let loggerTemplate = LiterateFormatting.tokeniserForOutputTemplate "[{level}] {timestampUtc:u} {message} [{source}]{exceptions}"
let singleLetterLogLevel = function Verbose->"V" |Debug->"D" |Info->"I" |Warn->"W" |Error->"E" |Fatal->"F"
let loggerOptions = { Literate.LiterateOptions.create() with getLogLevelText = singleLetterLogLevel }
let logger = LiterateConsoleTarget([|"Suave";"Example"|], Debug, options=loggerOptions, literateTokeniser=loggerTemplate) :> Logger 
```
<img width="1110" alt="screen shot 2017-02-10 at 12 09 24" src="https://cloud.githubusercontent.com/assets/570470/22811562/4d44a34e-ef8b-11e6-8fb7-617804f1bd03.png">

**Comment by adamchester** [comment]
I wonder if now would be a good time to add a similar feature to Logary proper?

**Comment by haf** [comment]
Nice, that would be good to put in the docs; I ended up modifying the default tokeniser in the Facade, like you'll see in the commits.

Feature parity is always a good idea :)
