### ISSUE TITLE
Can async timeout of 5000ms be optional/custom?

### ISSUE THREAD

**Issue by maxenko** [logary/logary#243]
https://github.com/logary/logary/blob/master/src/Logary.Facade/Facade.fs#L216

Running into a **cosmetic** issue with timeouts on massive (tens of thousands) of async queries to a database from suave.io which uses logary. It is expected in my case that some of these queries will come back minutes later. 

Is it possible to change api to optionally increase the timeout?

**Comment by haf** [comment]
@maxenko Glad you're pushing Suave and Logary towards their performance envelopes!

Is the database that returns with high latency, the Logary target? Otherwise, logging messages to Logary is expected to be concurrent to any long running operations.

**Comment by maxenko** [comment]
@haf 🙏 maybe I need to study it more. I am not specifying target explicitly anywhere. Here is one of the examples it is triggered by.

`                let userInsert () =
                    let guid = Guid.NewGuid().ToString()

                    async {
                        Log.info (eventX "Generating test user {s}." >> setFieldValue "s" guid)
                        let! usr = GetOrCreateUserAsync "TestApp" guid
                        let! usrId = getUserIdAsync appName guid
                        return usrId
                    }`

**Comment by haf** [comment]
What's your output?
