### ISSUE TITLE
Application Insights Targets feedback

### ISSUE THREAD

**Issue by SergeyKanzhelev** [logary/logary#246]
Thank you for the targets for Application Insights. Here is some feedback:

- [x] ~~I'd suggest to rename `AppInsights` to `ApplicationInsights` in NuGet name to avoid confusion. AppInsights is a different tool~~
- [x] ~~Also suggest to use full name for `AppInsightsKey`~~
- [x] ~~typically logger should take dependency on base SDK (`Microsoft.ApplicationInsights`). Reference to `Microsoft.ApplicationInsights.WindowsServer` will be added by user.~~
- [ ]  If you want to keep dependencies collection - please also add a standard telemetry initializer `HttpDependenciesParsingTelemetryInitializer` (like https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/401)
- [ ] Is it typical to target `4.5.2` for F# projects? Why not `4.6` or `4.5`?
- [x] ~~give a link to https://docs.microsoft.com/azure/application-insights/app-insights-create-new-resource in error message and comment `Enter your instrumentation key here. Get it from Azure Portal -> App Insights -> Properties -> INSTRUMENTATION KEY`~~
- [x] ~~Set `.Context.GetInternalContext().SdkVerion = "logary: <logary sem-version>"` to indicate that traces were collected by this adaptor. It will simplify troubleshooting if something goes not like expected.~~

**Comment by haf** [comment]
@Thorium I've given you write access to the repository to manage this target. :)

**Comment by Thorium** [comment]
Ok, thanks!

**Comment by haf** [comment]
<q> Is it typical to target 4.5.2 for F# projects? Why not 4.6 or 4.5?</q> – Not really – does it make a difference?

**Comment by SergeyKanzhelev** [comment]
@haf, target 4.5.2 force people to upgrade projects from 4.5, but do not go all the way to 4.6 where some new features like better correlation support are available.

**Comment by SergeyKanzhelev** [comment]
@Thorium I'll be happy to help with Application Insights questions. Ask in https://github.com/Microsoft/ApplicationInsights-Home/issues or mention me in issues.

**Comment by Thorium** [comment]
Is there more info about HttpDependenciesParsingTelemetryInitializer?

Logary targets were in general 4.5.2 so that's why I used it. I think it's convenient: It doesn't force you to do full update to .NET 4.6 (which can be problematic with some earlier MONO versions) and still it has many fixes that there has been for the old 4.5 for some time already.

**Comment by SergeyKanzhelev** [comment]
@Thorium this is what I thought about the 4.5.2.

In general we structure SDK so every data provider (we call them telemetry module) will be responsible for the specific data generation. And we have platform packages like `Web`, `WindowsServer`, `WCF`, `Asp.Net` (for ASP.NET Core). So mixing dependency data collector and logging adaptor is not aligned with the overall approach. 

If you want to keep the reference to dependency collection - please initializer `HttpDependenciesParsingTelemetryInitializer` so `HTTP` dependencies produced by dependency collection telemetry module would be parsed in case this http is an Azure blob or some other supported type of http dependency.

**Comment by Thorium** [comment]
@haf, how do I trigger a new version of target package to be generated? 
And how about renaming nuget package AppInsights to ApplicationInsights?

**Comment by haf** [comment]
Currently I build packages from my laptop; but I wouldn't mind setting up a build pipeline somewhere. Feel free to rename it; it's just been a single release.

**Comment by Thorium** [comment]
Renaming done... Now I would need a new package please. :-)

**Comment by Thorium** [comment]
@SergeyKanzhelev, about dependencies collection, what is your recommendation, should it be removed or does it actually have some usage?

**Comment by SergeyKanzhelev** [comment]
I think the best option will be to give instructions to customers on how to enable it separately from the logary targets.

**Comment by xuanduc987** [comment]
@Thorium 
I've tried this target with Suave app.
When exception occurs, `errors` field is show as `[Object]`.
Could we use something like `Formatting.MessageParts.formatValue` to get better log?

**Comment by Thorium** [comment]
Yes. Do you want to do a PR? :-)

**Comment by Thorium** [comment]
@haf can you update the Nuget package Logary.Targets.ApplicationInsights to contain @xuanduc987 's modifications? Also adding a manual notification to Nuget description of Logary.Targets.AppInsights that it's expired and go to  Logary.Targets.ApplicationInsights would be nice.

@xuanduc987: We should write a tutorial / blog-post how to configure a nice dashboard to ApplicationInsights to monitor a server with Logary-monitoring. Or is there already something like that somewhere?
