### ISSUE TITLE
format code-location(LocationInformation) in log4net adapter

### ISSUE THREAD

**Issue by lust4life** [logary/logary#256]
```fsharp
    let data =
      [ "app_domain",       box evt.Domain
        "thread_principal", box evt.Identity
        "code_location",    box evt.LocationInformation
        "thread_name",      box evt.ThreadName
        "user",             box evt.UserName ]
      |> Map.ofList
```

evt.LocationInformation has an StackFrames property, shall we customize it to a readability string here ? or we should do this job in the target level (find code_location field and format it there) ?

**Comment by haf** [comment]
I don't care much about the log4net adapter; if you care about it, I'll accept PRs towards it.

**Comment by lust4life** [comment]
ok

**Comment by lust4life** [comment]
handle by #219

**Comment by haf** [comment]
I honestly we can consider dropping log4net in the long run.

**Comment by lust4life** [comment]
this is the basic adapter, some old c# projects use log4net a lot, before migrate to logary , they can adapter first. 😄

**Comment by haf** [comment]
+1 then

**Comment by haf** [comment]
I have removed this as it caused a compiler error at some point.
