### ISSUE TITLE
event format proposal

### ISSUE THREAD

**Issue by lust4life** [logary/logary#257]
>In the new-engine branch; I'd love help with adding a 'known types' registry that is configurable per Logary instance; all others should have ToString() called on them.

#252   mentioned here, 

```f#
type Field =
  Field of Value * Units option 
```
i have a question, why Field have this signature , `Value * Units option`,  can we just use  `obj * Units option` , and if we have this signature, we can use FsMessageTemplates default format method ,and have the same consistency about (`$,@,align...`), and `adding a 'known types' registry` can by done by pass textwriter with `System.ICustomFormatter` ? 

use obj can have benefit when people what to custom their own `ToString` method， but this may can be done by `adding a 'known types' registry `  ?

another problem is , when we use `Value` ， we need call `Value.ofObject` ，it need support **ReferenceLoop** handling ? maybe ignore referenceloop or use a default maxDepth like **MessageTemplates ** , then it will not throw `StackOverflowException` when the object has a circle reference.

**Comment by haf** [comment]
Right; and the obj could still be of value `Value`, but boxed.

Then add the step/registry that converts to type `Value` from `obj`, doing ref-counting.

Then feed it into the targets.

Good.

**Comment by lust4life** [comment]
```fsharp
/// Logary's structured logging is centered around the `Value` type.
///
/// All objects logged into Logary are translated into a structure such as this
/// one.
///
/// The trade-off between passing all the CLR type information along versus
/// fitting it all into these cases is one of completeness versus convenience
/// in writing targets and computing on the data.
type Value =
  | String of string
  | Bool of bool
  | Float of float
...
```


in the new branch, i see some comments about `Value` type,`convenience` is good for `Gauge/Derived` doing some computing about metrics. but for `Event`, it has some limits, and the `fields` prop in `Message` make them loose coupling, `fields` should only for `Event` template rendering.

so shall we make some change like this:

```fsharp
type PointValue =
  /// Value at point in time
  | Gauge of Value * Units
  /// Any sort of derived measure
  | Derived of Value * Units
  /// All simple-valued fields' values can be templated into the template string
  /// when outputting the value in the target.
  | Event of template:string * args: obj []
```

the `args` is only for template rendering, we can supply an default format implementation use `FsMessageTemplates.sprintsm` (signature: `System.IFormatProvider -> string -> obj[] -> string`).

and every `Target` has its own `IFormatProvider` for this implementation. clients can add their own custom type render registry. maybe like `TemplateRender` below :

```fsharp
open System
open System.Globalization

type TemplateRender(innerFormatProvider : IFormatProvider) =

  let mutable dic:Map<string,(string * obj) -> string> = Map.empty

  member this.AddFormatDefault (func:('T) -> string) =
    this.AddFormat (fun (format,arg) -> func arg )

  member this.AddFormat (func:(string * 'T) -> string) =
    let wrapper (format, arg:obj) = func (format, unbox arg)
    dic <- Map.add (typeof<'T>.FullName) wrapper dic

  interface IFormatProvider with
    member this.GetFormat ty =
      match ty with
      | t when t = typeof<ICustomFormatter> -> this :> obj
      | _ -> innerFormatProvider.GetFormat ty

  interface ICustomFormatter with
    member this.Format (format : string, arg : obj, provider : IFormatProvider) =
      match arg with
      | _ when Map.containsKey (arg.GetType().FullName) dic ->
          dic.[arg.GetType().FullName] (format, arg)
      | :? IFormattable as f ->
          f.ToString(format, innerFormatProvider)
      | _ ->
          arg.ToString()


type FooBar = FooBar with
    member x.Name = "name is bar"

[<EntryPoint>]
let main argv =
    let tr = TemplateRender(CultureInfo.CurrentCulture)
    tr.AddFormatDefault  (fun num -> sprintf "int -> %i" num)
    tr.AddFormatDefault  (fun str -> sprintf "string -> %s" str)
    tr.AddFormatDefault  (fun (dt:DateTime) -> sprintf "datetime -> %s" (dt.ToString("yyyy-MM")))
    tr.AddFormatDefault  (fun (foobar:FooBar) -> sprintf "FooBar -> %s" foobar.Name)

    System.String.Format(tr,"date: {0}, number: {1}, foo: {2}",DateTime.Now, 42, FooBar) |> printfn "%s"
    // print ->
    // date: datetime -> 2017-06, number: int -> 42, foo: FooBar -> name is bar
    
    0 // return an integer exit code

```

and we can use it for custom templete rendering like this:

```fsharp
let renderMsg = FsMessageTemplates.sprintsm tr "date: {0}, number: {1}, foo: {2}" DateTime.Now 42 FooBar

let renderMsg = FsMessageTemplates.sprintsm tr eventTemplate eventArgs
```

and `ReferenceLoop` can be resovled by modify `FsMessageTemplates.tryObjectStructureDestructuring` support ref- couting or ref-check .

any suggestion?

**Comment by haf** [comment]
That's a nice solution to the problem. But what if the caller/logger user wants to use fields or context as part of the message?

**Comment by lust4life** [comment]
context is remained , like some extra info for message. but fields is only for template rendering.
if the caller/logger wants use fields as part of the message, they can do it in target. 
when target processing message, they can parse the template , generate the `PropToken` corresponding to their `list args obj` ,(`Map<PropToken,obj>`) . then doing its message processing. in here, they can use `typeshape` for some type checking/caching  like `value pattern match` used right now.

or maybe we should not expose the `Value` type to the log api , caller/logger log things use `obj` (even for context) , we can give the `target provider` choices: 
- transform these `obj` to `value` as they needed. 
- or use `typeshape` checking obj's underlying type, then use `Visitor` for their purpose ?

**Comment by haf** [comment]
I do like how your sample code fits. How about PRing it to this branch and we'll work with it.

**Comment by lust4life** [comment]
```fsharp
/// Logary's structured logging is centered around the `Value` type.
///
/// All objects logged into Logary are translated into a structure such as this
/// one.
///
/// The trade-off between passing all the CLR type information along versus
/// fitting it all into these cases is one of completeness versus convenience
/// in writing targets and computing on the data.
type Value =
  | String of string
  | Bool of bool
  | Float of float
...
```

I am wondering, if we let the user passing all CLR type wrapping in `object`, what's the difference between the pattern match about `Value` and `type test`, if the user can control the `Event Processing Builder`, they can type test what they log, and do something about them without lose info about origin type.

If the other purpose of `logging is centered around Value` is for getting some convenience when serialize message to `Json` in mostly targets. Because we(logary) have defined how to transfer `Message and Value` to json. At this situation, we can provide some default serialize method at logary for target. this default serialize method can use `TypeShape` checking data type, simulate something like `toJsonDefaults in Chiron`, if the data type does not provide `static member ToJson`, we can use reflection to provider an generic behavior. (like we use reflection when transform object to Value, but we defer this behavior, transform to what we want when needed, here is transform to Json when we need to serialize to target's backstore)

**Comment by haf** [comment]
Either we have an `obj` to `Value` function **before** the target, or we provide a convenient implementation thereof for targets to use. This function would do the pattern/type matching.

**Comment by lust4life** [comment]
@haf  i see you write some [converters for Newtonsoft.Json](https://github.com/haf/Newtonsoft.Json.FSharp) and recommend using `Chiron` , the chiron way for trasn data to json needs write each type's own serialization method. if we have a limited domain obj/types, that is very handy. but in a situation where we need a generic way to serialize obj which type we are not control even may not know. Is it possible(or necessary) to provide a common serialization method through reflection like you do in `Newtonsoft.Json.FSharp` but in `Chiron` ?

**Comment by haf** [comment]
The thing is that this library isn't about serialisation, so the Chiron serialisers are just there for the built-in structures. After all, didn't we decide to defer the translation of objects to the object model, until later; providing a default such translation function? That way; the object model is easily serialisable and you can inject more type shape visitors that transform your specific objects to the object model. It's not "just" a formatting concern.

So we don't need it.

**Comment by lust4life** [comment]
> and the obj could still be of value Value, but boxed.

> That way; the object model is easily serialisable and you can inject more type shape visitors that transform your specific objects to the object model

Yes, we can support some mechanism to register transformation on each target or global logary that transform user specific objects to `value model`. And the advantage of this is that we may not have to modify the existing targets implementations (because they need transform message to their underlying store, at present they are all working around `Value` ) and the `Formatting.fs` part (string Format, JSON serialization)

> After all, didn't we decide to defer the translation of objects to the object model, until later; providing a default such translation function?

Actually, I'm a little worried if we rely on `Value Model` to do these things. I think the `Value model` is something like an abstract model of the BCL type, somewhat like JSON, but we were not just building a data representation protocol. We also need to logically process this data somewhere (`Metric`,`Target`...), and these logic may depend on the information of the original object, but it is likely to be lost during the conversion process (to value model). And if what we do is just defer the translation, it doesn't solve the problem well. Because users may want to customize how their data is to be format to String/Json or other processing logic. One Value Model can not fit them all.

In the process of   `user send log -> registry route -> target`, on current version, because we have to deal with the `Metric` ourselves, so we have to deal with the `Value`. Such as in `Counter`, we only deal with `Value. Int64` of data.  But in the next version ( #263 ) , we have `Processing Builder` where users can define their own `Pipe`, so they know how to handle the data they log, without the need for our involvement.

so, the `Value Model`'s usage is only on targets implementation, i check all the target implementations and find out:

- some of them use just pattern match the type they care about,  which can be replaced by type check.
- some use `FsPickler.BinarySerializer`, nothing's going to change here.
- some transform `Value Model` to other type model (`Protobuf.WellKnownTypes`...), 
   
  but in this case, I think if we can preserve the original objects and then provide some basic types of conversions, and support registering specific transformations for them if they want to customize. **that will be more flexible and can do more things around the original object**. (e.g. invoke `ToString` method defined on origin object, something like this). 

   the main idea here is let the user decide how to transform their specific objects to the target's underlying "Type Model" directly, without intermediate layer (like what we do with `Value Model`). Then the targets implementor can focus the message "store" parts not the transformation parts and do less. 

- the majority of them is formatting to plain string or to json string. Essentially, they are just a type of the same thing talking above.

So, I'm thinking about whether we can remove the Value Type and use the native object. However, it may cause some more works on `targets and formatting`, which may be a little difficult to do compatibility.

**Comment by lust4life** [comment]
@haf  ping ? 😃

**Comment by haf** [comment]
Let's do it the way you suggest and let each target choose its way to transform CLR objects then.

The value model we use for metric and data and levels that we need to calculate on.
