### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by ajtribick** [logary/logary#259]
I was investigating this library earlier today and kept running into places where the documentation in the README.md file was incorrect. E.g. the example for "Logging from a class" includes an invalid multiplication, an undefined name "workName", and the signature of `Logger.time` does not match the example given.

The Rule & hierarchical logging section is also incorrect: the signature of Rule.createForTarget does not include the level parameter.

While the document indicates that there is a way to add file deletion and rotation policies, I had to delve into the code to figure out how to do this. An example here would be useful.

These are the main examples I ran into. While this looks like an interesting library full of useful features, the documentation lets it down and makes an unnecessary barrier for adoption.

**Comment by haf** [comment]
Thanks, but the amount of docs available, is never enough for some people. I've spend oodles of time into the readme and if you find errors in it, you're welcome to contribute via pull requests.
