### ISSUE TITLE
Use latest version of Crickets

### ISSUE THREAD

**Issue by haf** [logary/logary#27]
For version 2.0 I want to use the [released version](https://www.nuget.org/packages/FSharp.Actor/0.0.3-alpha) instead of the older 0.0.2 version currently in use.

Similar to current way of doing it, it's going to be built into [FSharp.Actor-logary](https://www.nuget.org/packages/FSharp.Actor-logary/) but with an identical code-base, as 1) not to conflict, 2) not to leave users of the logging library exposed to API changes and their respective ABI conflicts when installing.

There will be three major places where replacement causes code churn:

 - supervision - done differently
 - spawning and actor systems - actor systems are new and spawning/options API likely different
 - how to correlate requests with responses - I have my own 'rpc' API and make my actors block asynchronously, but we'd probably have to 1) post, 2) keep the original message in a list to work from, 3) when correlated response received, find original message/sender or update internal state until all responses are there.

**Comment by haf** [comment]
@colinbull Any and all help would be much appreciated

**Comment by colinbull** [comment]
@haf Yep, I can have a look at this.

**Comment by haf** [comment]
I started here https://github.com/logary/logary/tree/feature/use-crickets -- but there are a few things I haven't yet fully understood, so it's going slow.

**Comment by colinbull** [comment]
O.K, I have a slight problem in that I can't install Ruby to get the build working at work, so I'm gonna have to look at this in my spare time at home which might slow things down a little.

**Comment by haf** [comment]
Is there anything I can do to make it easier? Why can't you install ruby?

**Comment by colinbull** [comment]
It isn't just ruby I can't install anything. I have to have it pushed to me
from the powers that be in Apps Managment and they won't do ruby because it
isn't part of the tech stack. Sadly, it is the cost of working in a large
enterprise :(. It is one of the advantages of a FAKE based system for me at
least.. Not a problem, though I can get to it at home. I'm planning on
having a look this evening.

**Comment by haf** [comment]
I hope you're making a lot of :moneybag:  at least ;)

**Comment by colinbull** [comment]
JUst trying to setup my laptop for this evening (Ubuntu 14.04), and I'm getting a semver missing when running `bundle && bundle exec rake` however running `gem list` I can see 

     colin@colin-UX51VZA:~/Appdev/logary$ gem list 

      *** LOCAL GEMS ***

      albacore (2.3.15, 2.3.14)
      bundler (1.3.5) 
      map (6.5.5)
      mini_portile (0.6.2)
      net-http-persistent (2.9)
      nokogiri (1.6.5)
      rake (10.4.2)
      rdoc (3.9.4)
      semver2 (3.4.1, 3.4.0)
      thor (0.18.1.20140116)

It's been a while since I have been in the world of Ruby? What am I missing?

**Comment by haf** [comment]
Could you please post the stack trace?

You can run:

```
bundle exec gem list
bundle exec rake --trace DEBUG=true
```

and post the output. Thx.

**Comment by colinbull** [comment]
Gem list results:

     colin@colin-UX51VZA:~/Appdev/logary$ bundle exec gem list

     *** LOCAL GEMS ***

     albacore (2.3.14)
     bundler (1.3.5)
     map (6.5.5)
     mini_portile (0.6.2)
     nokogiri (1.6.5)
     rake (10.4.2)
     semver2 (3.4.0)

Rake Trace: 

     colin@colin-UX51VZA:~/Appdev/logary$ bundle exec rake --trace DEBUG=true
     rake aborted!
     LoadError: cannot load such file -- semver/semvermissingerror
     /var/lib/gems/1.9.1/gems/semver2-3.4.0/lib/xsemver.rb:2:in `require'
     /var/lib/gems/1.9.1/gems/semver2-3.4.0/lib/xsemver.rb:2:in `<top (required)>'
     /var/lib/gems/1.9.1/gems/albacore-2.3.14/lib/albacore/tasks/versionizer.rb:1:in `require'
     /var/lib/gems/1.9.1/gems/albacore-2.3.14/lib/albacore/tasks/versionizer.rb:1:in `<top (required)>'
     /home/colin/Appdev/logary/Rakefile.rb:4:in `require'
     /home/colin/Appdev/logary/Rakefile.rb:4:in `<top (required)>'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
     /var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
     /usr/local/bin/rake:23:in `load'
     /usr/local/bin/rake:23:in `<main>'

**Comment by haf** [comment]
Ok, could you please do

``` bash
gem env
echo $GEM_HOME_PATH
tree $GEM_HOME_PATH
```

and paste the details here?

You can try:

```
gem uninstall bundler -a
gem install bundler
bundle exec rake
```

Try restarting the shell and see if that helps.

You can also try to do:

```
bundle exec irb
require 'xsemver'
```

And paste the output.

We had that problem before: https://github.com/sstephenson/rbenv/issues/660 but he 'fiddled' with it. Unfortunately I can only give you a fiddle, but can't fiddle with your stuff.

**Comment by colinbull** [comment]
colin@colin-UX51VZA:~$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.23
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
  - INSTALLATION DIRECTORY: /var/lib/gems/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/1.9.1
     - /home/colin/.gem/ruby/1.9.1
     - /usr/share/rubygems-integration/1.9.1
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/

**Comment by haf** [comment]
Let me see if I can't reproduce it myself.

I'm going to use a clean ubuntu box.

**Comment by haf** [comment]
The reason is that you've installed some gem (probably semver) as root and the folder doesn't have read permissions for other groups or others.

I've created a devbox for you:

https://github.com/logary/devbox

**Comment by colinbull** [comment]
Cool, although I think I have fixed it, or the build has at least started. Basically I had actually got two versions of ruby, installed and that was causing bundler to have a heart attack... Having said that I might just use the devbox anyway.

**Comment by haf** [comment]
Let me debug the box a bit more...

**Comment by colinbull** [comment]
I have a working build now anyway..

**Comment by haf** [comment]
That should do it. zlib1g-dev damnit!!

**Comment by haf** [comment]
I've done some updates to the naming of Logary, so I've pushed v3.0 (semver accordingly). You might want to rebase before you go deeper.

How is it going, btw? =)

**Comment by colinbull** [comment]
O.K will do, Had a few hours over the weekend, to look at how things tie together and see where actors are used, there is a fair amount to get your head round. I need to collect my thoughts and I'll drop you an e-mail / skype at some point just to make sure I'm on the right track. Initially thou it looks like though some things will need to be added to Cricket, so there is parity with the FSharp.Actor API.

**Comment by haf** [comment]
I have skype; `h.feldt` - when is best for you? Tomorrow?

**Comment by colinbull** [comment]
Prob, be Thurs.. But I'll confirm.

**Comment by haf** [comment]
Closing in favour of Hopac.
