### ISSUE TITLE
Logger.apply

### ISSUE THREAD

**Issue by haf** [logary/logary#273]
```

module Logger =
  let apply fn (logger: Logger) =
    let nameIfMissing = function
      | m when m.name.Length = 0 ->
        { m with name = logger.name }
      | m -> m

    { new Logger with
        member x.name = logger.name
        member x.log level messageFactory =
          logger.log level (messageFactory >> nameIfMissing >> fn)
        member x.logWithAck level messageFactory =
          logger.logWithAck level (messageFactory >> nameIfMissing >> fn)
    }
```

**Comment by lust4life** [comment]
will [ensurename](https://github.com/logary/logary/blob/master/src/Logary/Internals_Logger.fs#L35) handle  this ?

**Comment by lust4life** [comment]
get your point,  [live-wpc-reconfigure](https://github.com/logary/logary/blob/feature/live-wpc-reconfigure/src/Logary/Internals/Global.fs#L83-L93) will handle this

**Comment by haf** [comment]
It replaces

```
    let nameIfMissing = function
      | m when m.name.Length = 0 ->
        { m with name = logger.name }
      | m -> m
```

from the function above, but the thing with `apply` is that it allows you to create new loggers.

In my apps, I pass an enriched logger down to the layer below, from the layer above.

**Comment by lust4life** [comment]
i got what you mean, `fn` here needs to get the message name (if missing use the logger name) too, is this what you want ?

[right now, the ensurename](https://github.com/logary/logary/blob/master/src/Logary/Internals_Logger.fs#L66) just ensure name before generate msg and send to target. it is in the end of this processing .

**Comment by haf** [comment]
`fn` is any of the `Message -> Message` functions on the `Message` module; as such it can be used to create new logger instances that always have some given context/field.
