### ISSUE TITLE
Using logary in WPF app

### ISSUE THREAD

**Issue by StefanBelo** [logary/logary#277]
How should I use logary to display logs in WPF grid control of running app?

What should be implemented, adapter, target or service?

**Comment by haf** [comment]
You can choose different architectures of that. One way is to spawn a service like Rutta does (a ZMQ socket) in your WPF app and send all logs to it using the Shipper target you can find on NuGet.

You'd have to update the buffer in some smart way. You'd have to know how to stitch pieces of code together, but most you'll find in Rutta+Shipper.

**Comment by haf** [comment]
PS; another way, if you're just logging from within your own WPF application and not from outside, is to create a Target that displays the logs it gets and just add that to Logary.

**Comment by StefanBelo** [comment]
In windows desktop apps the main problem is UI thread from which anything can be added to app model. 

Yes, I tried to create new target, but code is failing with: Field not found: 'NodaTime.SystemClock.Instance'.

I used Targets_Noop.fs as suggested, and made just:

``

**Comment by StefanBelo** [comment]
My naïve, or better to say stupid reasoning as I cannot follow most of code in logary is following:

In UI apps, I want to setup logary to write logs in 1 second batch queue if possible. App can generate 100-1000 of logs per second but from UX perspective is enough for logary to display new logs in app in 1 second interval for instance.  

Any adding operation must be executed in UI thread therefor I tried to write my custom AppLogary target, as in "Log (message, ack) -> .."  thread context must be switched to UI one. I am not sure how batch of logs/messages can be processed, as it would be waste of resources to switch for any new log message, better approach is switching to UI context then write all logs, and then switch back to original job thread.

I hope you understand what I wanted to say as my English is not so good.

**Comment by haf** [comment]
@StefanBelo What you're describing is an optimisation. Start by writing to your observable collection when you get log messages, see how it goes.

Then you can introduce a timer which is renewed every time you loop as a pre-condition; something like;

```fsharp
let rec loop nextUpdate =
  nextUpdate ^=> fun () ->
  Alt.choose [
    shutdown...
// snip
    RunBuffer.takeBatch 1000 ^=> function
      | messages ->
        job {
          Dispatcher.InvokeOnUIThread(fun () -> config.OutputDatas.AddRange(messages))
          // ack the range of messages here (see Influx or RMQ target for instance)
          return! loop (timeOutMillis 1000)
        }
// snip
```

**Comment by StefanBelo** [comment]
Thanks haf, of course I must familiarize myself with Hopac and your logary code. Dispatcher.InvokeOnUIThread is so C# - ish, actually if you think about it, the same use case scenario can be applied to file streaming logs, so not to write per message request to the file stream, but in bigger chunks/batches.

Thereof I thought logary can be configured, without any programming to process logs as I wanted. Then when you think further in my use case scenario, I want to transform message to log model displayed in app UI.

That all can be simply done by offering Target allowing to process messages in batch and taking a transform function in target configuration.

Unfortunately, I cannot compile your logary library to test examples and logary code on my computer. I downloaded logary and RingBuffer projects, but still files you link in logary projects are missing:

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0225	Source file 'C:\Work\Samples\logary-master\src\Logary\..\..\paket-files\xyncro\aether\src\Aether\Aether.fs' could not be found	Logary	FSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0225	Source file 'C:\Work\Samples\logary-master\src\Logary\..\..\paket-files\xyncro\chiron\src\Chiron\Chiron.fs' could not be found	Logary	FSC	1	Active

and so on.

**Comment by haf** [comment]
Did you try just running `build.cmd`?

**Comment by StefanBelo** [comment]
You use paket, it is executed by VS when clicking on build. I tried paket install, and build. Solution building fails with errors missing:

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0225	Source file 'C:\Work\Samples\logary-master\src\Logary\AssemblyVersionInfo.fs' could not be found	Logary	FSC	1	Active

In all projects where AssemblyVersionInfo.fs is included.

Buil.cmd can be found only in:

logary-master\examples\Logary.IntroSlides

and yes here presentation is build correctly.

**Comment by haf** [comment]
You're on an old version; it is there: https://github.com/logary/logary/blob/master/build.cmd
