### ISSUE TITLE
Possible adapter additions

### ISSUE THREAD

**Issue by TheAngryByrd** [logary/logary#282]
I have a set of adapters I've been using over here: https://github.com/TheAngryByrd/LogaryTools/tree/master/src

```
Logary.Adapters.AspNetCore
Logary.Adapters.Hangfire	
Logary.Adapters.Marten	
Logary.Adapters.NpgSql	
Logary.Adapters.Owin
```

I didn't originally contribute these as I was trying to wait until a netstandard version of logary.  Now that 5.0 is netstandard, would you like to see any of these contributed back to main logary?

**Comment by haf** [comment]
Hello @TheAngryByrd 

Thank you for the offer. I've done some cleaning in the repository and one thing I cleaned was the targets not being upgraded by their authors. So my main decision point is really if I get help to maintain this in a timely fashion. 

That said, if you publish them on your own and upgrade them for Logary v5, it's really not a bad idea to keep them separate. I'm trying to avoid impediments to the development of Logary and nugets changing their public API and not maintaining semver has historically been a large impediment to keep Logary up to date.

**Comment by TheAngryByrd** [comment]
Sounds good, I like the idea of keeping them separate but I figured I would ask before doing such.  Thanks as always!!

**Comment by haf** [comment]
As you say, it's a trade-off. If I could get more help from the original authors of the targets to maintain them, I'd happily put them in separate repos, but when refactoring a full new release, it's pretty nice to have them together. We currently have a 4 minute build time, which is alright, despite the # of repos. Contrast with 30m+ for e.g. OpenCV.

So right now I think we'll leave it at this and keep the builds green

**Comment by lust4life** [comment]
ok
