### ISSUE TITLE
Uncoment influx data sending for v5

### ISSUE THREAD

**Issue by haf** [logary/logary#283]
/cc @lust4life 

https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.InfluxDb/Targets_InfluxDb.fs#L59

**Comment by haf** [comment]
Done

**Comment by lust4life** [comment]
apologize again for not following up. still looking at your latest updates (nice work by the way), will try to migrate `aliyun.target` to net core version.

**Comment by haf** [comment]
@lust4life No worries. If you could write basic code for

 - https://github.com/logary/logary/issues/255
 - and https://github.com/logary/logary/issues/21#issuecomment-351447380
 - and how to continously ship a reservoir, alike Logary.ConsoleApp.Timing
 - and possibly the timing of async/job/alt and .bisect and child loggers with context/middleware

That would be of the highest leverage right now.

— In the docs; featuring the best sides of the new stream processing, that would be great. :)

**Comment by lust4life** [comment]
ok, will take a look
