### ISSUE TITLE
StringFormatters output newlines

### ISSUE THREAD

**Issue by haf** [logary/logary#285]
/cc @adamchester @lust4life 

Question for you: `Logary/Formatting/StringFormatter.LevelDatetimePathMessageNl complex data`

Outputs a huge chunk

It's safe to say the literate console is the thing people will debug with. Then: the string formatters should output single lines... Could you guys have a look at the tests for formatting, make sure they work across different Thread.CurrentCulture values and perhaps make them all (unless specified otherwise) output a single line with the data?

**Comment by adamchester** [comment]
Just confirming ... the formatters, when combined together, sometimes output too much data. So we will try to ensure they’re limited to a single line. @haf do you have a sample you can paste here that shows “too much data” and/or too many lines?

**Comment by haf** [comment]
I think we have two use-cases:

 - debug logging, which I think LiterateConsole is better at
    * debug logging single line mode: can literate console be configured for this?
    * debug logging expanded with all fields/props/context/exns: basically like it is now?
 - console logging for e.g. systemctl/journalctl type of logs with a log-per-line: which I'm asking for here; this is the reason the above string formatter ends with `Nl`, as in new-line, to be specific that it doesn't output more than a single line. "normal console logging" should then be enabled at >= Warn levels in production and always log single lines. It could output more data than is in the `message.value` field though; as long as it's a single line.

**Comment by haf** [comment]
Sorry, it's not this issue that is fixed. The tests are passing, but the newline based formatters should still not print with newlines them for the console.

**Comment by haf** [comment]
I think that for non-literate console logging which is what LevelDateTimePathMessageNl was for we should by default output only single lines.

For anything else, I think we should leave it like this and show how to use MessageWriter with the targets.

**Comment by lust4life** [comment]
#292 does this help ?

**Comment by haf** [comment]
I'm finding that I'm still missing docs for how to do it with the literate console.

**Comment by lust4life** [comment]
@haf  misunderstanding your needs before.  for `literate console.` 
 https://github.com/logary/logary/blob/master/src/Logary/Targets/Core.fs#L208-L209

**Comment by adamchester** [comment]
Yeah actually I made an attempt at creating one last night, but lots has changed so I got side tracked often. I think that’s the basic idea, just make a replacement for that function.

I think the default for literate is good readability for a human. I think humans would want a new line separating exceptions and maybe other common elements, right?

**Comment by haf** [comment]
@adamchester Yes that is true; but in my use-case I need to debug a pretty verbosely logging service and the extra lines makes that impossible; the terminal can't hold all the text and most of the time of the developer goes to scrolling up and down and not finding what they want. That said; the extra space comes from the context always being printed and not from the exceptions. Perhaps we provide three variants; context + exn + line, exn + line and line-only + exn message?

**Comment by adamchester** [comment]
I agree @haf.

I think we should introduce a similar concept which the Facade got first already in #234 and #247 (i.e. a customisable output template with built-in fields like `{properties}`, `{exception}`, and so on...). I think this output template feature is much easier to use than composing your own `tokenise` function.

I'm not sure when I would have time to tackle this myself, it could be days, weeks, months, or years away, but it *is* something I want to do.

In the short term, I think we have inadvertantly prevented people from copying the built-in tokenise function with some internals, so we can make those public somehow, and also expose a few pre-built functions like you have suggested which cover the most common use cases out of the box.

**Comment by haf** [comment]
Done in beta.4.
