### ISSUE TITLE
How to specify content type?

### ISSUE THREAD

**Issue by haf** [logary/logary#288]
@adamchester How would I specify a log message with a `byte[]` and an annotation with a content type attached?

/cc @lust4life

**Comment by adamchester** [comment]
Just to help me understand a bit better.... how would you have done this before, without it being part of the message? 

The first thing that comes to mind is using a record type with two properties (data + content type). Would that work?

**Comment by lust4life** [comment]
this can be done with the old `Value` type,
```fsharp
type Value =
  ...
  | Binary of byte [] * ContentType
  ...
```

now: 
```fsharp
/// Allows you to clearly deliniate the accuracy and type of the measurement/gauge.
type Value =
  /// A CLR Double / F# float represented as a DU case
  | Float of float
  /// A CLR Int64 / F# int64 represented as a DU case
  | Int64 of int64
  | BigInt of bigint
  | Fraction of int64 * int64
```
since we restrict the `Value` DU for  gauge value around numbers, it lose this ability. users needs create their own type(DU,record) for this. since your new json format can automatic encode all these value, they can be easily showed on the target's backend.

```fsharp
  let configProjection projectionExpr =
    Logary.Internals.Global.Destructure.configProjection projectionExpr

  let configDestructure<'t> (factory: CustomDestructureFactory<'t>) =
    Logary.Internals.Global.Destructure.configDestructure<'t> factory

  let configJsonEncoder<'t> (factory: CustomJsonEncoderFactory<'t>) =
     Logary.Internals.Global.Json.configJsonEncoder<'t> factory
```

we have already provider mechanism for users register the [format processing logic](https://github.com/logary/logary/blob/master/src/Logary/Configuration/Config.fs#L148-L155)  for their arbitrary type, i think this will not be a problem.

**Comment by haf** [comment]
So basically, either;

```fsharp
type Binary = Binary of data:byte [] * contentType:ContentType
// or
type Binary =
  { data: byte[]; contentType: ContentType }
```

and then

```fsharp
logger.info (eventX "Got {pic}" >> setField "pic" (Binary (stream.ToArray(), "image/jpeg")))
```

Would that format A-OK with the literate console?

**Comment by haf** [comment]
Also note: I haven't added back the JSON registry to the new Json formatter.

**Comment by lust4life** [comment]
`Would that format A-OK with the literate console?`
theoretically ok 😄 , will try this later.

**Comment by lust4life** [comment]
![image](https://user-images.githubusercontent.com/3074328/38350666-e4b815ec-38de-11e8-89b4-db3cd9a7bbbf.png)

is this what you want ?

**Comment by haf** [comment]
Good enough. A bit funky to get output in terms of JSON, though? DOn't you think? Can't we reuse the destructor used for printing the main log message after `[FTL]` ?

**Comment by lust4life** [comment]
the default destructor take `Record` as `POCO`, so it just invoke its `ToString` method. and since it is in the message template, so we escape the newline character.

**Comment by haf** [comment]
Ok, let's leave it at this. Thanks for the documentation.
