### ISSUE TITLE
Add `addGaugeP: PointName -> Gauge -> Message -> Message` for point names

### ISSUE THREAD

**Issue by haf** [logary/logary#311]

**Comment by lust4life** [comment]
can we change gaugeName as the `obj`, then use `.ToString()` to get the string name. the will not add more signatures. but since `PointName` is a `Struct`, will involve boxing/unboxing

**Comment by haf** [comment]
But if we just add a `-P` function, we don't have to do the boxing. Isn't this better? We can to-string the gauge name before adding it to as a field of the context.
