### ISSUE TITLE
Exclude one exception type from logging

### ISSUE THREAD

**Issue by Thorium** [logary/logary#320]
How do I set log-level for a single exception type to have different priority than others?

I use a library that is using an anti-pattern to code their business-logics exceptions as custom type technical exceptions. I don't want to write manual catches to everywhere, I just want to say "hey Logary, don't fill my primary error log with this spam from the library".

What would be the best way to do this?

**Comment by haf** [comment]
```
let isSpam m =
  m |> Message.getExns |> function
    | (e :? SpamException) :: exns -> true
    | _ -> false
...processing (
  Events.events  |> Pipe.filter isSpam   |> Events.sink [ "spam" ]
  |> Events.events |> Pipe.filter (isSpam >> not) |> Events.sink ["otherwise"]
)
```

Perhaps? I could also use some help to solve the Events-related issues in this issue tracker in order to document splitting on more than one variable /cc @lust4life

**Comment by Thorium** [comment]
Thanks for the response, this raises more questions. :-)
1) What is the difference with `Message.setContextValue` and `Message.setField` ?
2) I don't have `Message.getExns` what is that?
3) Can I reset the existing level something like:
```fsharp
>> withMiddleware (fun next msg ->
        msg |> Logary.Message.getExns |> function
              | (e :? SpamException) -> (msg |> Message.setLevel LogLevel.Warn)
              | _ -> msg)
```

**Comment by haf** [comment]
What version are you on? https://github.com/logary/logary/blob/master/src/Logary/MessageModule.fs#L510

setField sets fields, which are per-message mostly, while context is per-logger mostly.

**Comment by Thorium** [comment]
The last stable, 4.2.1. :-)

**Comment by haf** [comment]
Also, yes you can use a middleware to change the level if you want.
