### ISSUE TITLE
Seq as Target

### ISSUE THREAD

**Issue by Rajivhost** [logary/logary#321]
Hi,
Any plan to provide [Seq](https://getseq.net/) as target?

Best regards,
Rajiv.

**Comment by haf** [comment]
Greetings Rajiv,

No plans; it was a target a few years back but was removed due to lack of upkeep. If you'd be willing to pay a monthly fee I can add it for you, otherwise, it's really easy to create new targets nowadays; have a look at the Noop target in the code-base for a commented example.
