### ISSUE TITLE
waitForBuffers handling in processing?

### ISSUE THREAD

**Issue by haf** [logary/logary#348]
```
Unhandled exception: System.Exception: logWithAck (true, _) should have waited for the RingBuffer(s) to accept the Message. Target(console)
```

**Comment by lust4life** [comment]
#378   , log error can be handled by config a result handler on [`registry`](https://github.com/logary/logary/blob/e92e460db5c1ecc9c56e18007101846ca688d5c1/src/Logary/Registry.fs#L272-L277) , and [ the default one ](https://github.com/logary/logary/blob/e92e460db5c1ecc9c56e18007101846ca688d5c1/src/Logary/Configuration/Config.fs#L49)

**Comment by haf** [comment]
@lust4life Thanks, so with your PR, this should be fixed, I suppose? Since you switched from 'rejected' as the default to 'accepted' as the default?

**Comment by lust4life** [comment]
these are two different things, if target not accept a message,this will result a log error message to registry's logErrorHandler.

changing pipeline processing result （NoResult) to acceptable is for fire-forget. e.g. user log a message, goto a pipe which have a buffer sink, it will only push to target by batches. So at this logging time, this message are in pipe's buffer, not in target, but we assume that this logging result is success.
