### ISSUE TITLE
Planned license-related changes

### ISSUE THREAD

**Issue by haf** [logary/logary#351]
- [x] Move Facade v4 to Apache 2.0 for use with libraries
 - [x] Specify license for Rutta;  GNU (never linked/used inside app)?
 - [x] logary-js; MIT
 - [x] Logary proper; Change wording to make it free for F# web servers and app frameworks. In the end, it's free if the software runs without complaining. If license check evolves and it was free before evolution, e-mail me and you get a license for free.
    [ ] EULA like Commons Clause but for _ usage in any commercial activity_
 - [x] Improve wording away from "general design" in license; by moving to BSD3 license to license commercially under; triggered by above.
 - [x] Add a clear CLA for contributions/pull requests
 - [x] Add license FAQ to LICENSE.md.
 - [x] Make support options explicit as extra add-on to commercial license.
 - [ ] ~Create a web site; must be easy to maintain~
 - [ ] ~Create a dotnet core template showcasing a full setup with Suave, Expecto, Influx, Grafana~
 - [x] Enable `requireLicenseAcceptance` in nuget package
 - [x] Go through all code that is due for relicensing;
    * Verify which bits need attribution explicitly under Apache 2.0.
 - [x] Make it [even clearer](https://github.com/haf/expecto/issues/256#issuecomment-399021028) how the Facade can connect to things

Timeline: for v5 GA release.

 - `src/Logary`: dual licensed
 - `README.md` and all docs: [CC SA](https://creativecommons.org/licenses/by-sa/2.5/)
 - `src/Logary.Facade`: Apache 2.0
 - `src/targets`: dual licensed; some are derived work by others; go through git history
 - `src/adapters`: dual licensed
 - `src/services/Rutta`: [GNUv3 Lesser](http://www.gnu.org/copyleft/lesser.html) or purchase commercial
 - `src/tests`: dual licensed
 - `src/logary-js`: dual licensed

Reading:

 - http://www.jus.umu.se/digitalAssets/13/13669_jan_eriksson_leido.pdf
 - https://medium.com/@liftm/commons-clause-isnt-that-bad-df3ea7c93996

**Comment by ReedCopsey** [comment]
>  Logary proper; Change wording to make it free for F# web servers and app frameworks. 

I'm curious how you intend to write this. Even Suave, for example, uses and is built on top of non-F# code/libraries internally (libuv, all of the templating engines, etc).

**Comment by haf** [comment]
@ReedCopsey Very liberally; as a dialogue between people rather than technical enforcement. Targeting what web servers and app frameworks that I know of and having the single technical license check in place is enough.

**Comment by wallymathieu** [comment]
Looks like @haf did quite a lot of work for the 5.0.0 release. How does the licensing of Logary affect Suave?

**Comment by haf** [comment]
@wallymathieu There's no effect to Suave what so ever, stemming from this change.

**Comment by wallymathieu** [comment]
@varon is it that in the docs https://safe-stack.github.io/docs/template-overview/ Suave is not mentioned (while Saturn is in the first place). In the template there seems to still be [ServerSuave.fs](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Server/ServerSuave.fs) so it does not look removed (just no mentioned). Do you have some more info about it?

**Comment by wallymathieu** [comment]
Indeed, that was what I expected @haf, since Suave does not depend on Logary.

**Comment by varon** [comment]
@wallymathieu @haf https://safe-stack.github.io/docs/news/#18th-june

**Comment by wallymathieu** [comment]
@varon thanks, that makes things clearer

**Comment by wallymathieu** [comment]
It would perhaps be beneficial to have a default non commercial version of Logary 5 (that does not contain the performance changes) so that you can opt in to the high performance version if you have the budget for it. I think I've seen somewhere that Logary5 has the same API surface as Logary4, so the same adapter should be able to be used in both cases?

**Comment by haf** [comment]
@varon It would seem like you're angry with me and that has nothing to do with Suave. I can't say I care much that you're angry with me. After all, you've never give me anything and I've only given you free stuff, so I don't feel obliged to change based on just "I'm angry I can't have this project that I've never contributed substantially to, free any more".

**Comment by wallymathieu** [comment]
From what I can see the license change is in a not yet released version 5.0.0? @haf has significantly rewritten parts of the code base and gotten a sign off from the other major contributors to relicense. 

There are other companies on the .net platform choosing to have paid licenses :
- [servicestack](https://servicestack.net/)
- [imageresizing](https://imageresizing.net/)
- [ravendb](https://ravendb.net/)
So, companies having open source nuget packages that requires a license key is not something new. 

If Logary facade is supposed to be used as an f# logging abstraction, then keeping the facade under apache2 makes sense. However you would then expect to be able to have an alternate implementation compatible with the facade.

The wording in the license can be improved to make it clearer what he and the other core contributors are trying to accomplish.

**Comment by varon** [comment]
@haf The licensing changes don't affect my usage. I'm frustrated because you seem to be trying to direct the F# community according to _your_ vision, which is contrary to the community's values.

If this the direction you think is best for the F# community, then continue as you please. If not, then I advise you to re-think this licensing change.

**Comment by haf** [comment]
@varon What *are* those values in you opinion?

**Comment by varon** [comment]
@haf Everyone is trying very hard to get more people involved and using F#. We're doing this by keeping things open and free, being friendly, and most of all including anyone who wants to join.

**Comment by haf** [comment]
@varon I think the way you and your friends have been very unfriendly lately. Beyond that I don't see how this conflicts in any way besides perhaps open: open to what is probably the question there. Open to having paid OSS available is probably not one of those things. Open to extension and collaboration over forking and owning is what I'm aiming for.

**Comment by varon** [comment]
@haf It conflicts on the point of inclusivity.

It shouldn't matter what web server you decide to use any more than what someone's favourite colour might be. The license explicitly excludes members of the community that happen have a different preference to you.

**Comment by haf** [comment]
@varon Commercial web servers go under a commercial license; but for the hundredth time, what this thread is about is to discuss **what** license to use to convey that — hence no conflict. Feel free to come with constructive suggestions and alternatives instead.

**Comment by varon** [comment]
Just make logary require a commercial license if used for profit.

**Comment by surfmuggle** [comment]
The link to the pdf from jan leido is broken. It seems that this search has currently no matching hit: https://www.google.com/search?client=firefox-b&ei=rTkdXPWIM8PXwQKX3qDYBA&q=Legal+issues+with+mixed+source+software+in+a+commercial+environment+jan+leido&oq=Legal+issues+with+mixed+source+software+in+a+commercial+environment+jan+leido&gs_l=psy-ab.3...31998.88249..88794...0.0..0.247.9334.64j35j1......0....1..gws-wiz.....0..0j0i8i30j0i30j0i22i30j33i22i29i30j33i21j33i160j33i10.Ce4UJgMMLiY

**Comment by haf** [comment]
@surfmuggle It was a longer article on what rights are presumed in different continents due to their respective judicial systems. Logary is under European/Swedish jurisdiction for the purposes of licensing; which is not the same as the USA. It's a complex world we live in.

**Comment by haf** [comment]
Please see the new [LICENSE.md](https://github.com/logary/logary/blob/master/LICENSE.md) document.

**Comment by haf** [comment]
We could use the jest of an agreement like this https://developercertificate.org/ in for sending pull requests, beyond the LICENSE.md document.
