### ISSUE TITLE
Prometheus exporter?

### ISSUE THREAD

**Issue by haf** [logary/logary#361]
Of health/metrics

 + http://marselester.com/prometheus-on-kubernetes.html

**Comment by lust4life** [comment]
and logs ?
- https://schd.ws/hosted_files/kccna18/99/Kubecon%202018_%20Full%20Observability%20with%20OSS%20%281%29.pdf
- https://grafana.com/loki#faq

**Comment by lust4life** [comment]
@haf  Do you think we need to implement a client library, or only the exporter ? or make a adapter to client like https://github.com/prometheus-net/prometheus-net

**Comment by lust4life** [comment]
@haf  and what do you think ?

**Comment by haf** [comment]
I think we can leave out the push API for now, and get some marketing done on this feature; just having the endpoint for polling available is a huge boon to the default state of .net apps.

**Comment by haf** [comment]
Solving in favour of #395
