### ISSUE TITLE
Hopac 0.4.1 Coexistence

### ISSUE THREAD

**Issue by abk-x** [logary/logary#370]
```
$ dotnet new console -lang F#
$ dotnet add package hopac --version 0.4.1
$ dotnet add package logary --version 4.2.1
```

Change Program.fs to
```
open NodaTime
open Hopac
open Logary
open Logary.Configuration
open Logary.Targets
open Logary.Metric
open Logary.Metrics

let logary = 
    withLogaryManager "Logger" (
        withTargets [
            LiterateConsole.create LiterateConsole.empty "console"
        ]
        >> withRules [ Rule.createForTarget "console"]
        )
    |> Hopac.Hopac.run

let logger = Logging.getLoggerByName "Test"
```

dotnet run crashes with:
```
Unhandled Exception: System.MethodAccessException: Attempt by method 'Logary.Supervisor.create(Logary.Logger)' to access method 'Hopac.Job+Global.startIgnore<Microsoft.FSharp.Core.Unit>(Hopac.Job`1<Microsoft.FSharp.Core.Unit>)' failed.
   at Logary.Supervisor.create(Logger logger)
   at Logary.Registry.Advanced.create(LogaryConf conf)
   at Logary.Configuration.Config.RunLogary(LogaryConf conf)
   at Logary.Configuration.Config.WithLogaryManager(String serviceName, FSharpFunc`2 fConf)
   at <StartupCode$crap>.$Program.main@() in /tmp/crap/Program.fs:line 12
```

### Workaround
`dotnet add package hopac --version 0.3.23`

Dotnet version:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6
```

**Comment by haf** [comment]
This is true and good docs.

It's not actionable, as nothing is broken.

Thank you for reporting it and helping fellow googlers! With v5 you can use the latest Hopac.

**Comment by haf** [comment]
@btrepp All that is needed for v5 is to complete the license work #351 In short:

 - per folder licenses
 - gnu-like for open source/non profit
 - nice contractual license jurisdiction Sweden for commercial
 - copyright assignment via PR-bot for commercial license
 - after the above, non-blocking for v5, I'd like something that lets me distribute income according to contribution ratio, with a default distribution to e.g. the red cross or other charity

v5 is now more stable than v4, despite being in beta.
