### ISSUE TITLE
try add a target for jaeger tracing

### ISSUE THREAD

**Issue by lust4life** [logary/logary#379]
since we have `span` in logary, this can make some adapter for jaeger through https://github.com/jaegertracing/jaeger-client-csharp/tree/master/src/Jaeger.Thrift 

- https://github.com/opentracing/specification/blob/master/specification.md
- https://www.jaegertracing.io/
- https://www.nuget.org/packages/Jaeger.Thrift/

**Comment by haf** [comment]
This would be amazing!

**Comment by haf** [comment]
BTW; you should add AspNetCore into this repo IMO.

**Comment by lust4life** [comment]
if i can put aspnetcore in this repo, it will become more convenient for update state with logary, otherwise i need wait for you releasing a nuget pkg, then sync it with aspnetcore-adapter.

will try to do this migration after #380 , will you give a look at there ?

**Comment by haf** [comment]
@lust4life #380 is fine, but needs to pass CI before merge.

Sure, after that is merged sounds fine

**Comment by haf** [comment]
@lust4life Now finally, I got the FAKE file right and have pushed a release! https://www.nuget.org/packages/Logary/5.0.0-rc.1 I'm sorry about this looooong delay.

**Comment by lust4life** [comment]
@haf  thx, will check it later , that is very nice.
