### ISSUE TITLE
release new version about Targets.AliYun/Adapters.AspNetCore

### ISSUE THREAD

**Issue by lust4life** [logary/logary#406]
@haf  can you help release the corresponding new version of Targets.AliYun/Adapters.AspNetCore these two packages ?

**Comment by haf** [comment]
I think you need to give me access to it https://www.nuget.org/packages?q=Adapters.AspNetCore+

**Comment by lust4life** [comment]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/3074328/54527220-2e39ed80-49b4-11e9-8bb6-7f64ff8d8870.png">
done.

**Comment by haf** [comment]
Alright thx. Is it added to the fsx file for libraries to build packages for?

**Comment by lust4life** [comment]
![image](https://user-images.githubusercontent.com/3074328/54581391-76562000-4a47-11e9-918f-18d4f5c99b88.png)

yes. it can generate nupkgs in pkg folder.

**Comment by haf** [comment]
very good, I'll release it shortly; do you have access to release yourself? Would you like access?

**Comment by lust4life** [comment]
I think i don't have access to release `Targets.AliYun` and `Target.Jaeger`, but should probably have access to `Adapters.AspNetCore`,  since these proj depend on `logary`, when release, they need release logary too.

**Comment by haf** [comment]
Done, manually.

**Comment by lust4life** [comment]
thx , will try it later.
