### ISSUE TITLE
Clarification of commercial licensing requirements

### ISSUE THREAD

**Issue by aggieben** [logary/logary#418]
In LICENSE.md:

> Non-profits and non-profit projects are free to use without payment, subject to the Terms of Service defined below.
> 
> For-profit or commercial entities must purchase licenses to use Logary for their production environments, subject to the Terms of Service defined below.

I'm not sure how to apply this to my own situation, which is that I have some code I'm working on that has a permissive license (Apache 2) and is currently nothing more than a hobby project, but the copyright is held by a commercial entity and I have plans for it to be used commercially at some point.  Do I need a commercial license because I have assigned copyright to a commercial entity?  If I don't need a commercial license and I work on this for a while and begin to use the project commercially in some way, is it only when deployed to a production environment that a license is required?

I really like your work and want to be able to make use of it - but I want to make sure I'm doing what's required and I'm just not clear on what I need to do.

**Comment by haf** [comment]
What bits of Logary are you using? If it's the Facade, it's licensed separately from the Logary proper library, which is separate from Rutta in its license. I don't think what other the other code's license is, matters that much. The intention is not so much about copyright, but about using the library proper in commercial software.

>  is it only when deployed to a production environment that a license is required?

Yes

I actually launched a new pricing calculator today! 🎇 🎉 https://logary.tech/pricing

**Comment by aggieben** [comment]
I plan to use the façade and library backend to write to console + log file sinks for the forseeable future.  I could possibly imagine using the prometheus bits, but probably not Rutta, at least not in the near term.

**Comment by haf** [comment]
The facade is forever free of charge, so no worries there.

The file target requires the facade adapter + logary, so that's what you'd pay for in production then. The facade has a literate console output built in.

I'm closing this issue; feel free to ask more questions if you have them though.
