### ISSUE TITLE
Invalid certificate for the website

### ISSUE THREAD

**Issue by simendsjo** [logary/logary#434]
https://logary.tech/logary-dotnet-quickstart

![image](https://user-images.githubusercontent.com/351519/73209896-73d55400-4149-11ea-99ce-5f5454676bd1.png)

**Comment by haf** [comment]
Thanks for alerting me to it. I'll try and fix it today.

**Comment by haf** [comment]
Fixed in b7d1bcde6084450b01ddc80248e24b8ced4f5ae3 — now all I need is good docs, too!
