### ISSUE TITLE
Enrichers

### ISSUE THREAD

**Issue by futurechan** [logary/logary#68]
# Support a pipeline that has support for enrichers, amongst other things
![logary](https://cloud.githubusercontent.com/assets/193115/9378364/2b1e2358-4721-11e5-99dd-918443880918.png)

**Comment by haf** [comment]
Not at this point, I'm afraid.

We could improve the Logger implementation to also resolve a number of 'advice', so that each Rule that matches can attach advice to the resolved Logger instance, and then each LogLine from that Logger would have the enriched content in its `data` Map.

**Comment by futurechan** [comment]
That would be fantastic.

**Comment by futurechan** [comment]
Would the 'advice' be able to map all parts of a log4net log message by default?

**Comment by futurechan** [comment]
Also, I've been looking at creating a MassTransit logger. I'm not sure how to approach the conversion of a log object to a string. Any thoughts?

**Comment by haf** [comment]
Well, it would act on a LogLine / Measure, not the raw log4net log item, so it wouldn't *map* them, but you could easily create advice for all relevant data items that log4net attaches.

**Comment by haf** [comment]
The log object is just a string; see the TopShelf adater: https://github.com/logary/logary/blob/master/src/adapters/Logary.Adapters.Topshelf/Topshelf.LogaryLogWriter.fs#L28-L30

**Comment by haf** [comment]
Being solved by #110
