### ISSUE TITLE
Missing method exception occurred in Logary.Suave.dll

### ISSUE THREAD

**Issue by darting** [logary/logary#75]
Hi,

This is the error message:

```
An unhandled exception of type 'System.MissingMethodException' occurred in Logary.Suave.dll
Additional information: Method not found: 'Int64 Suave.Logging.LogLine.get_ts_utc_ticks()'.
```

I installed it from Nuget, the version is:
Logary (3.3.2)
Logary.Suave (2.6.0)
Suave (0.29.0)

is it the latest version of Logary.Suave in Nuget?

thanks

**Comment by haf** [comment]
Logary.Adapters.Suave

https://www.nuget.org/packages/Logary.Adapters.Suave/
