### ISSUE TITLE
Structured or Templated Messages

### ISSUE THREAD

**Issue by haf** [logary/logary#79]
See

 - https://github.com/adamchester/MessageTemplates/issues/1
 - https://github.com/akkadotnet/akka.net/issues/1045
 - https://github.com/SuaveIO/suave/issues/270

## Logary Implementation

The v4.0's structures apply. The new `Fields list` type should be used as a source of values to template into the message.

The spec linked above dictates the pretty-printing.

The LogLine message itself may or may not contain templated place-holders; the important part is that it is hash-able and doesn't vary (for a given semantic logging context) so that statistics on the logs can be compiled by dashboards.

Work together on the structured values and their implementations.

**Comment by haf** [comment]
Fixed in #90

**Comment by adamchester** [comment]
:clap:

**Comment by nblumhardt** [comment]
Awesome :-) :fireworks:
