### ISSUE TITLE
Hello-world console: System.MissingMethodException was unhandled

### ISSUE THREAD

**Issue by Thorium** [logary/logary#93]
I'm trying to get started here... The latest NuGet package Logary (3.5.0) and source code:

    open System
    open Logary
    open Logary.Configuration
    open Logary.Targets

    [<EntryPoint>]
    let main args = 
        let logary = 
            withLogary "MyTest" (
                withTargets [
                    Console.create Console.empty "console"
                ] >> withRules [
                    Rule.createForTarget "console"
                ]
            )
        let logger = Logging.getCurrentLogger ()
        LogLine.info "Hello World!" |> logger.Log

Throws:

    System.MissingMethodException was unhandled
    Message: An unhandled exception of type 'System.MissingMethodException' occurred in Unknown Module.
    Additional information: Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2<System.String,TargetConf> Logary.Targets.Console.create(ConsoleConf)'.

So what sould I do to be able to use `Console.create Console.empty "console"` ?

**Comment by haf** [comment]
I'm not sure; have you ensures you have the proper F# core rebinds? If it compiles it should work, basically.

**Comment by Thorium** [comment]
As a testing I use just standard .NET Framework v.4.5.1 console application with F# runtime 4.3.0.0 and I don't have any rebinds.
It does compile, but runtime fails.

**Comment by Thorium** [comment]
Solved!

Changing from .fsproject-file from this:

    <Reference Include="FSharp.Core>
      <Private>True</Private>
    </Reference>

...to this:

    <Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <Private>True</Private>
    </Reference>

changed the project's Target F# runtime option from disabled grayed 4.3.0.0 to changeable default 4.3.1.0 and then the Logary also started working.
