### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by JorritSalverda** [logary/logary#96]
Currently it seems that Logary doesn't support the upcoming .net core. 

In order to create a nuget package that supports the old .net framework and the new upcoming .net core you can target frameworks **net45** and **dotnet** (the latter covering both .net framework 4.6 and .net core). I've done this with https://github.com/JorritSalverda/JitterMagic, which then separately shows both frameworks in the dependencies on nuget.org, see https://www.nuget.org/packages/JitterMagic.

Building the package is done with following commands (in appveyor at least):

```
dnvm upgrade -r coreclr
set DNX_ASSEMBLY_FILE_VERSION=%APPVEYOR_BUILD_NUMBER%
dnu restore
dnu build --configuration Release **/project.json
dnu pack --configuration Release src/*
```

More detailed information on how to convert packages to support .net core is in these blog posts:
- http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html
- http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-2.html
- http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html

What are the plans on supporting .net core?

**Comment by haf** [comment]
I haven't yet made any plans, because F# on .Net Core isn't yet fully baked. Perhaps that has changed now? It would make a great PR to add the support.

**Comment by haf** [comment]
So it would seem .Net Core *is* fully baked now and we're also looking to see what can be done to support our use-cases for it.

If your company has made the mode or is making the move I'd be up for cooperating around that.

**Comment by haf** [comment]
Corresponding Hopac thread https://github.com/Hopac/Hopac/issues/114

**Comment by TheAngryByrd** [comment]
Has there been any progress/pitfalls on this?  If not I'll start trying to port it this weekend.

**Comment by haf** [comment]
Only that me and some others worked through Hopac, which now works on .Net core, so progress. Other than that; no pitfalls. I've bumped .Net to 4.6.1 which now is supported by mono.

**Comment by quintusm** [comment]
I would be willing to help with this if it would be useful.  Getting F# working nicely on dotnetcore 2 and up is a key scenario for my organization

**Comment by haf** [comment]
It sure would be useful. See #275 — we're moving towards v5

**Comment by Thorium** [comment]
I think the netstandard2.0 / netcoreapp2.0 is easier target than the current trial to convert it to netstandard1.6. I know 2.0 wasn't ready earlier.

**Comment by TheAngryByrd** [comment]
I've been on and off making the build work for .net core but pulling over so many projects has kind of been a real time sink.  

I can give you commit rights to https://github.com/logary/logary/pull/204 or you can use it as a starting point.

**Comment by quintusm** [comment]
Everybody happy if we target netstandard2 and not worry about earlier versions of netcore?  It seems to me that there was a lot of missing things in earlier versions.

**Comment by TheAngryByrd** [comment]
Yeah it'd make it easier.  Less ifdefs.  The only thing I noticed that  may or may not affect Logary 5 is the benchmarking.  I haven't looked at the PR extensively but I know using it on dotnet core the ticks are different.

http://aakinshin.net/blog/post/stopwatch/

Important part:

>Now let's consider the Linux+TSC case. On Mono, we have Resolution = 100 ns because it is the value of 1 tick (and it can be achieved). On CoreCLR, 1 ticks is 1 ns

**Comment by lust4life** [comment]
> It sure would be useful. See #275 — we're moving towards v5 
@quintusm  @TheAngryByrd  , i think it is preferably consider doing it base on [this branch 'live-wpc-reconfigure'](https://github.com/logary/logary/tree/feature/live-wpc-reconfigure) , or merge it - the sooner the better.

**Comment by quintusm** [comment]
Ok I will have a look at that branch, was a bit preoccupied for a couple of days but will be starting in earnest soon.  I might have some questions which I will raise here as I run into them

**Comment by lust4life** [comment]
any progressing or plan here, want to see if i can join to give a hand ?

**Comment by lust4life** [comment]
@TheAngryByrd  @quintusm   https://github.com/logary/logary/compare/feature/live-wpc-reconfigure...dotnet-core-v5?expand=1

does the porting something like this ?

**Comment by quintusm** [comment]
Hi @lust4life, no progress to report on my side, sorry.  Got stuck with some other issues.  I should be able to start on this in more earnest tomorrow.  Would appreciate any help...

**Comment by Inkp** [comment]
So, is there any progress or something that should be helped with?

**Comment by quintusm** [comment]
HI @Inkp @lust4life 
I am afraid that some stuff has popped up in my personal life and I do not have the time available that I anticipated to work on this.  I would still love to get involved in future but for now you should assume that I am not working on this or available to assist. My apologies...

**Comment by haf** [comment]
@quintusm I've done the work in the linked branch. I just tried to release it, but I have 2FA enabled and that doesn't fly with default fake installation.

**Comment by haf** [comment]
@Inkp PLease do test the v5 branch linked above; it should be easy to compile and the readme has been updated.

**Comment by haf** [comment]
Merged to master; there may be merge issues I haven't found. Need to make 4 tests pass too. That could use some help
